import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../frontend/package.json',import.meta.url));
const {PGlite}=require('@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon nologin; create role authenticated nologin; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
for(const file of ['001_fase1.sql','002_fase2.sql','004_bitacora_fondos.sql'])await db.exec(await readFile(new URL('../migrations/'+file,import.meta.url),'utf8'));
const a='30000000-0000-0000-0000-000000000001',c='30000000-0000-0000-0000-000000000002',w='30000000-0000-0000-0000-000000000003',p='20000000-0000-0000-0000-000000000001';
await db.exec(`insert into auth.users values('${a}'),('${c}'),('${w}');
 insert into corporaciones(id,nombre) values('${p}','Prueba');
 insert into personal(id,cuip,nombre_completo,corporacion_id,adscripcion) values('${p}','TEST001','Persona ficticia','${p}','Prueba');
 insert into usuarios(id,rol,personal_id) values('${a}','admin',null),('${c}','capacitacion',null),('${w}','trabajador','${p}');`);
const login=async(id,role='authenticated')=>db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role ${role};`);
const denied=async(fn,code)=>{try{await fn();assert.fail('Expected denial');}catch(e){assert.equal(e.code,code,e.message);}};
const update=async(version,key,value,section='values')=>(await db.query('select actualizar_bitacora_fondo($1,$2,$3,$4,$5::jsonb) as value',['FASP',version,section,key,JSON.stringify(value)])).rows[0].value;
await login(c);
assert.equal((await db.query('select * from bitacora_fondos')).rows.length,2);
await denied(()=>db.exec("update bitacora_fondos set version=99"),'42501');
const doc=await update(1,'J3','2026-11-03');assert.equal(doc.version,2);assert.equal(doc.data.values.J3,'2026-11-03');
await denied(()=>update(1,'B3','stale'),'P0001');
await denied(()=>update(2,'B2','fake heading'),'22023');
await denied(()=>update(2,'J4','2026-11-03'),'22023');
await denied(()=>update(2,'J3','2030-01-01','receipts'),'22023');
await denied(()=>update(2,'B3','2026-10-05','receipts'),'22023');
await denied(()=>update(2,'J3','invalid date'),'22023');
await denied(()=>update(2,'B3',{}),'22023');
await update(2,'J3','2020-01-01','receipts');
await login(w);
assert.equal((await db.query('select * from bitacora_fondos')).rows.length,0);
await denied(()=>update(3,'B3','not allowed'),'42501');
await login(a);
assert.equal((await db.query("select * from auditoria where tabla='bitacora_fondos'")).rows.length,2);
await db.exec('reset role');await db.query('update usuarios set activo=false where id=$1',[c]);
await login(c);assert.equal((await db.query('select * from bitacora_fondos')).rows.length,0);
await denied(()=>update(3,'B3','disabled'),'42501');
await login(a,'anon');await denied(()=>db.exec('select * from bitacora_fondos'),'42501');
console.log('Bitácora: RLS, permisos, fechas, celdas combinadas, auditoría y conflictos verificados.');
await db.close();
