import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../frontend/package.json',import.meta.url));
const {PGlite}=require('@electric-sql/pglite');
const db=new PGlite();let checks=0;
const check=(v,m)=>{assert.ok(v,m);checks++;};
await db.exec(`create role anon nologin; create role authenticated nologin; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
for(const f of ['001_fase1.sql','002_fase2.sql'])await db.exec(await readFile(new URL('../migrations/'+f,import.meta.url),'utf8'));
// Minimal Storage schema for SQL policy checks; the real Storage HTTP service is not simulated.
await db.exec(`create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant usage on schema storage to authenticated,anon;
grant select,insert,delete on storage.objects to authenticated;`);
await db.exec(await readFile(new URL('../migrations/003_evidencias.sql',import.meta.url),'utf8'));
const A='30000000-0000-0000-0000-000000000001',C='30000000-0000-0000-0000-000000000002',W='30000000-0000-0000-0000-000000000003',V='30000000-0000-0000-0000-000000000004';
const P='20000000-0000-0000-0000-000000000001',Q='20000000-0000-0000-0000-000000000002',CORP='10000000-0000-0000-0000-000000000001';
await db.exec(`insert into auth.users values('${A}'),('${C}'),('${W}'),('${V}');
insert into corporaciones(id,nombre) values('${CORP}','Corporación ficticia');
insert into personal(id,cuip,nombre_completo,corporacion_id,adscripcion) values('${P}','TEST001','Persona uno','${CORP}','Área A'),('${Q}','TEST002','Persona dos','${CORP}','Área B');
insert into usuarios(id,rol,personal_id) values('${A}','admin',null),('${C}','capacitacion',null),('${W}','trabajador','${P}'),('${V}','trabajador','${Q}');`);
async function login(id,role='authenticated'){await db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role ${role};`);}
async function rpc(fn,args){const keys=Object.keys(args);return (await db.query(`select ${fn}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as value`,Object.values(args))).rows[0].value;}
async function denied(fn,code='42501'){try{await fn();assert.fail('Expected rejection');}catch(e){assert.equal(e.code,code,e.message);checks++;}}
await login(C);
const course=(await db.query(`insert into cursos(nombre_curso,tipo,fuente_financiamiento,institucion_impartidora,horas) values('Curso de prueba','actualizacion','FASP','Academia',40) returning *`)).rows[0];
const session=(await db.query(`insert into curso_sesiones(curso_id,fecha_inicio,fecha_fin,sede,modalidad,cupo) values($1,current_date,current_date,'Aula 1','presencial',1) returning *`,[course.id])).rows[0];
const enroll=(pid,status='inscrito')=>rpc('guardar_inscripcion',{sesion:session.id,datos:JSON.stringify({personal_id:pid,estatus:status,calificacion:null})});
await enroll(P);
await denied(()=>enroll(Q),'P0001');
await enroll(P,'en_curso');
check((await db.query('select * from inscripciones')).rows.length===1,'Update is idempotent per person/session');
await enroll(P,'baja');await enroll(Q);await denied(()=>enroll(P),'P0001');
await db.query('update curso_sesiones set cupo=2 where id=$1',[session.id]);await enroll(P);
await denied(()=>db.query('update curso_sesiones set cupo=1 where id=$1',[session.id]),'P0001');
check((await db.query('select inscripciones_visibles from vw_curso_sesiones')).rows[0].inscripciones_visibles===2,'Staff sees all enrollments');
const activity={sesion_id:session.id,fecha:'2024-01-01',tipo_actividad:'avance',descripcion:'Actividad de prueba'};
await denied(()=>rpc('guardar_bitacora',{datos:JSON.stringify(activity)}));
await login(W);
check((await db.query('select * from inscripciones')).rows.length===1,'Worker sees own enrollment');
check((await db.query('select inscripciones_visibles from vw_curso_sesiones')).rows[0].inscripciones_visibles===1,'View respects worker enrollment RLS');
await denied(()=>enroll(Q));
await denied(()=>db.query(`insert into cursos(nombre_curso,tipo,fuente_financiamiento,institucion_impartidora,horas) values('Prohibido','actualizacion','FASP','Academia',40)`));
const entry=await rpc('guardar_bitacora',{datos:JSON.stringify({...activity,personal_id:Q})});
check(entry.personal_id===P,'RPC derives owner, ignores forged identity');
const path=`${P}/${entry.id}/40000000-0000-0000-0000-000000000001.pdf`;
await db.query("insert into storage.objects(bucket_id,name) values('bitacora-evidencias',$1)",[path]);
const evidence=await rpc('vincular_evidencia',{entrada:entry.id,datos:JSON.stringify({ruta:path,nombre:'test.pdf',tipo:'application/pdf',tamano:100})});
check(evidence.bitacora_id===entry.id,'Owner attaches private evidence');
check((await db.query('delete from storage.objects where name=$1 returning *',[path])).rows.length===0,'Attached evidence cannot be deleted');
await denied(()=>db.query("insert into storage.objects(bucket_id,name) values('bitacora-evidencias',$1)",[path.replace('000001.pdf','000002.pdf')]));
await denied(()=>rpc('guardar_bitacora',{datos:JSON.stringify({...activity,fecha:'2099-01-01'})}),'22023');
await denied(()=>db.query('update bitacora set descripcion=$1 where id=$2',['Cambio directo',entry.id]));
await login(V);
check((await db.query('select * from bitacora')).rows.length===0,'Other worker cannot read journal');
check((await db.query('select * from storage.objects')).rows.length===0,'Other worker cannot read evidence objects');
check((await db.query('select * from bitacora_evidencias')).rows.length===0,'Other worker cannot read evidence metadata');
await denied(()=>rpc('vincular_evidencia',{entrada:entry.id,datos:JSON.stringify({ruta:path,nombre:'test.pdf',tipo:'application/pdf',tamano:100})}));
await denied(()=>rpc('guardar_bitacora',{datos:JSON.stringify(activity),entrada:entry.id}));
await login(A);
check((await db.query('select * from bitacora')).rows.length===1,'Admin can consult journal');
check((await db.query('select * from storage.objects')).rows.length===1,'Admin can read evidence');
const data={cuip:'NEW001',curp:null,nombre_completo:'Persona importada',sexo:null,corporacion_id:CORP,adscripcion:'Área C',cargo_id:null,grado_id:null,estatus:'activo'};
const stage=(rows)=>rpc('preparar_carga',{datos:JSON.stringify({nombre_archivo:'prueba.csv',tipo_archivo:'csv',tabla_destino:'personal',filas:rows})});
const row={fila:2,personal_id:null,version:null,datos:data,errores:[]};
const batch=await stage([row]);
check((await db.query('select * from personal')).rows.length===2,'Preview does not write personal');
const confirmed=await rpc('confirmar_carga',{carga:batch.id});
check(confirmed.registros_procesados===1,'Import applies valid row');
await rpc('confirmar_carga',{carga:batch.id});
check((await db.query('select * from personal')).rows.length===3,'Confirm retry has no duplicate writes');
const conflict=await stage([{...row,datos:{...data,cuip:'NEW002'}},row]);
await denied(()=>rpc('confirmar_carga',{carga:conflict.id}),'23505');
check((await db.query("select * from personal where cuip='NEW002'")).rows.length===0,'Conflict rolls back entire batch');
const old=(await db.query('select updated_at::text as version from personal where id=$1',[P])).rows[0].version;
const stale=await stage([{...row,personal_id:P,version:old,datos:{...data,cuip:'TEST001'}}]);
await db.query('update personal set adscripcion=$1 where id=$2',['Cambio concurrente',P]);
await denied(()=>rpc('confirmar_carga',{carga:stale.id}),'P0001');
const bad=await stage([{...row,errores:['Error de ejemplo']}]);
await denied(()=>rpc('confirmar_carga',{carga:bad.id}),'22023');
await login(C);check((await db.query('select * from carga_archivos')).rows.length===0,'Imports admin only');
await denied(()=>stage([row]));await denied(()=>rpc('confirmar_carga',{carga:batch.id}));
await login(W);await denied(()=>stage([row]));
await db.exec(`reset role;update usuarios set activo=false where id='${W}';`);await login(W);
check((await db.query('select * from cursos')).rows.length===0,'Disabled user cannot read courses');
await denied(()=>rpc('guardar_bitacora',{datos:JSON.stringify(activity)}));
await login('','anon');await denied(()=>db.query('select * from cursos'));await denied(()=>rpc('confirmar_carga',{carga:batch.id}));
await db.exec('reset role');check((await db.query("select * from auditoria where tabla='bitacora'")).rows.length>=1,'Journal writes audited');
await db.close();console.log(`${checks} verificaciones de fase 2 correctas: RLS, cupos, bitácora y transacciones de carga.`);
