import {FormEvent,useEffect,useState} from 'react';
import {Check,Download,FileSpreadsheet,Upload} from 'lucide-react';
import {api,download} from '../api';
import {dateLabel,ErrorBox,label,Loading,Page,Pager,useData} from '../components';
type Row={fila:number;identificador:string;accion:string;origen:Record<string,string>;datos:Record<string,unknown>;errores:string[]};
type ImportRecord={id:string;nombre_archivo:string;tabla_destino:string;estado:string;registros_procesados:number;registros_error:number;fecha_carga:string;expires_at:string;filas:Row[]};
export function Imports(){
 const [target,setTarget]=useState('personal'),[file,setFile]=useState<File|null>(null),[record,setRecord]=useState<ImportRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[offset,setOffset]=useState(0);
 const history=useData<Page<ImportRecord>>('/carga-masiva?offset='+offset);
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{setNow(Date.now());if(!record||record.estado!=='revision')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[record]);
 function selectFile(candidate:File|null){setRecord(null);setError('');setFile(null);if(candidate&&(!/\.(xlsx|csv)$/i.test(candidate.name)||candidate.size>2*1024*1024||!candidate.size)){setError('Selecciona un archivo XLSX o CSV no vacío, de hasta 2 MB.');return;}setFile(candidate);}
 async function preview(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError('');setRecord(null);try{const data=new FormData();data.append('destino',target);data.append('archivo',file);setRecord(await api<ImportRecord>('/carga-masiva/previsualizar',{method:'POST',body:data}));setOffset(0);history.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirm(){if(!record||busy)return;setBusy(true);setError('');try{setRecord(await api<ImportRecord>(`/carga-masiva/${record.id}/confirmar`,{method:'POST'}));history.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function getFile(path:string,name:string){setError('');try{await download(path,name);}catch(e){setError((e as Error).message);}}
 async function open(id:string){if(busy)return;setBusy(true);setError('');setRecord(null);try{setRecord(await api<ImportRecord>('/carga-masiva/'+id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const expired=record?new Date(record.expires_at).getTime()<=now:false;
 return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRACIÓN DE INFORMACIÓN</span><h1>Carga masiva</h1><p>Importa personal o evaluaciones desde Excel y CSV, con revisión antes de guardar.</p></div><FileSpreadsheet size={36}/></div>
 <div className="import-steps"><span className={!record?'current':''}>1. Preparar archivo</span><span className={record?.estado==='revision'?'current':''}>2. Revisar filas</span><span className={record?.estado==='confirmada'?'current':''}>3. Confirmar carga</span></div>
 <form className="surface phase-form" onSubmit={preview}><h2>Seleccionar archivo</h2><div className="form-grid"><label>Información a importar<select value={target} onChange={e=>{setTarget(e.target.value);setRecord(null);}} disabled={busy}><option value="personal">Estado de fuerza</option><option value="competencias_basicas">Competencias básicas</option></select></label><label>Archivo Excel o CSV *<input type="file" accept=".xlsx,.csv" required disabled={busy} onChange={e=>selectFile(e.target.files?.[0]??null)}/><small>Máximo 2 MB y 200 filas; una sola hoja por libro.</small></label></div><div className="import-help"><strong>Usa los encabezados de la plantilla</strong><p>{target==='personal'?'CUIP o CURP, nombre completo, corporación y adscripción son obligatorios. Usa los nombres exactos de los catálogos. Los campos opcionales vacíos conservan el valor existente.':'CUIP o CURP debe coincidir con un expediente. Usa fechas AAAA-MM-DD y resultado aprobado o no_aprobado. Las evaluaciones anteriores se conservan como historial.'}</p><div className="action-row">{['xlsx','csv'].map(f=><button type="button" key={f} className="text-button" onClick={()=>getFile(`/carga-masiva/plantilla?destino=${target}&formato=${f}`,`plantilla-${target}.${f}`)}><Download size={16}/>Plantilla {f.toUpperCase()}</button>)}</div></div><div className="form-actions"><button className="button primary" disabled={!file||busy}><Upload size={18}/>{busy?'Procesando…':'Revisar archivo'}</button></div></form>
 <ErrorBox message={error}/>{busy&&!record&&<Loading/>}{record&&<section className="table-panel"><div className="panel-heading"><div><h2>{record.estado==='confirmada'?'Carga completada':'Revisión del archivo'}</h2><p className="muted">{record.nombre_archivo} · {label(record.tabla_destino)}</p></div><button className="button secondary" onClick={()=>getFile(`/carga-masiva/${record.id}/reporte`,'reporte-carga.csv')}><Download size={16}/>Reporte</button></div><div className="import-summary"><span><strong>{record.filas.length}</strong> filas</span><span><strong>{record.filas.filter(r=>r.accion==='insertar').length}</strong> altas</span><span><strong>{record.filas.filter(r=>r.accion==='actualizar').length}</strong> actualizaciones</span><span className={record.registros_error?'error-text':''}><strong>{record.registros_error}</strong> filas con error</span></div>
 {record.estado==='confirmada'?<div className="success" role="status"><Check size={18}/>{record.registros_procesados} registros guardados correctamente.</div>:<p className="import-notice">{record.registros_error?'Corrige las filas indicadas y vuelve a subir el archivo. Todavía no se ha modificado ningún expediente.':expired?'La revisión caducó. Vuelve a subir el archivo para validar la información actual.':'Revisa las altas y actualizaciones. Al confirmar, se guardará el lote completo. La revisión vence una hora después de su carga.'}</p>}
 <div className="table-scroll import-preview"><table><thead><tr><th>Fila</th><th>Identificador / acción</th><th>Datos del archivo</th><th>Validación</th></tr></thead><tbody>{record.filas.map(r=><tr key={r.fila}><td>{r.fila}</td><td><strong>{r.identificador||'Sin identificador'}</strong><small>{label(r.accion)}</small></td><td><details><summary>{r.datos.nombre_completo?String(r.datos.nombre_completo):r.origen.folio||'Ver datos'}</summary><dl className="preview-data">{Object.entries(r.origen).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{v||'—'}</dd></div>)}</dl></details></td><td>{r.errores.length?<ul className="row-errors">{r.errores.map((e,i)=><li key={i}>{e}</li>)}</ul>:<span className="badge status-vigente">{record.estado==='confirmada'?'Guardado':'Validado'}</span>}</td></tr>)}</tbody></table></div>{record.estado==='revision'&&<div className="form-actions import-confirm"><button className="button primary" disabled={busy||record.registros_error>0||expired} onClick={confirm}>{busy?'Guardando…':`Confirmar ${record.filas.length} registros`}</button></div>}</section>}
 <section className="table-panel history"><div className="panel-heading"><h2>Mis cargas recientes</h2></div><ErrorBox message={history.error}/>{history.error&&<button className="text-button" onClick={history.reload}>Reintentar historial</button>}{history.loading&&<Loading/>}<div className="table-scroll"><table><thead><tr><th>Archivo</th><th>Fecha</th><th>Estado</th><th>Procesados / errores</th><th>Acciones</th></tr></thead><tbody>{history.data?.items.map(r=><tr key={r.id}><td>{r.nombre_archivo}<small>{label(r.tabla_destino)}</small></td><td>{dateLabel(r.fecha_carga)}</td><td>{label(r.estado)}</td><td>{r.registros_procesados} / {r.registros_error}</td><td><button disabled={busy} className="text-button" onClick={()=>open(r.id)}>Consultar</button></td></tr>)}</tbody></table></div>{!history.loading&&!history.data?.items.length&&!history.error&&<div className="empty">Aún no has cargado archivos.</div>}<Pager disabled={history.loading||busy} offset={offset} more={history.data?.has_more??false} onChange={setOffset}/></section></>;
}
