import {FormEvent,useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {CalendarDays,ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {api} from '../api';
import {User,Person} from '../types';
import {allPages,dateLabel,ErrorBox,label,Loading,Page,Pager,today,useData} from '../components';
export type Course={id:string;nombre_curso:string;tipo:string;fuente_financiamiento:string;institucion_impartidora:string;horas:number;vigencia_meses:number|null};
export type Session=Course&{curso_id:string;fecha_inicio:string;fecha_fin:string;sede:string;modalidad:string;cupo:number;estatus:string;inscripciones_visibles:number};
export type Enrollment={id:string;personal_id:string;sesion_id:string;estatus:string;calificacion:number|null;personal:{nombre_completo:string;cuip:string|null};curso_sesiones:{fecha_inicio:string;fecha_fin:string;cursos:{nombre_curso:string}}};
const types=['formacion_inicial','competencias_basicas','actualizacion','especialidad'];
const statuses=['inscrito','en_curso','concluido','baja'];

export function Calendar({user}:{user:User}){
 const [month,setMonth]=useState(today().slice(0,7)),[view,setView]=useState('calendario'),[form,setForm]=useState(''),[revision,setRevision]=useState(0);
 const [sessions,setSessions]=useState<Session[]>([]),[courses,setCourses]=useState<Course[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [year,m]=month.split('-').map(Number),days=new Date(Date.UTC(year,m,0)).getUTCDate(),start=month+'-01',end=month+'-'+days;
 const staff=user.rol!=='trabajador';
 const [editingCourse,setEditingCourse]=useState<Course|undefined>();
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.all([allPages<Session>(`/curso-sesiones?desde=${start}&hasta=${end}`,controller.signal),allPages<Course>('/cursos',controller.signal)]).then(([s,c])=>{if(!controller.signal.aborted){setSessions(s);setCourses(c);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[start,end,revision]);
 function move(delta:number){const d=new Date(Date.UTC(year,m-1+delta,1));setMonth(d.toISOString().slice(0,7));}
 const blanks=(new Date(start+'T12:00:00Z').getUTCDay()+6)%7;
 const monthLabel=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(start+'T12:00:00Z'));
 return <><div className="page-heading"><div><span className="eyebrow">PROGRAMACIÓN Y SEGUIMIENTO</span><h1>Calendario de cursos</h1><p>Consulta las sesiones, sus fechas y la formación disponible.</p></div>{staff&&<div className="action-row"><button className="button secondary" onClick={()=>{setEditingCourse(undefined);setForm(form==='curso'?'':'curso');}}>Nuevo curso</button><button className="button primary" onClick={()=>setForm(form==='sesion'?'':'sesion')}><Plus size={18}/>Programar sesión</button></div>}</div>
 {form==='curso'&&<CourseForm key={editingCourse?.id??'new'} existing={editingCourse} onSaved={()=>{setForm('');setRevision(n=>n+1);}} onCancel={()=>setForm('')}/>}
 {form==='sesion'&&<SessionForm courses={courses} onSaved={()=>{setForm('');setRevision(n=>n+1);}} onCancel={()=>setForm('')}/>}
 <div className="calendar-legend"><span className="legend-next">Próximo</span><span className="legend-active">En curso</span><span className="legend-ended">Concluido</span></div><section className="table-panel"><div className="panel-heading calendar-toolbar"><div className="action-row"><button className="icon-button" aria-label="Mes anterior" onClick={()=>move(-1)}><ChevronLeft size={20}/></button><h2>{monthLabel}</h2><button className="icon-button" aria-label="Mes siguiente" onClick={()=>move(1)}><ChevronRight size={20}/></button><button className="text-button" onClick={()=>setMonth(today().slice(0,7))}>Hoy</button></div><div className="segmented">{['calendario','agenda'].map(v=><button key={v} aria-pressed={view===v} className={view===v?'active':''} onClick={()=>setView(v)}>{label(v)}</button>)}</div></div>
 <ErrorBox message={error}/>{loading?<Loading/>:error?<button className="button secondary" onClick={()=>setRevision(n=>n+1)}>Reintentar</button>:view==='calendario'?<div className="calendar-scroll"><div className="calendar-grid">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length:blanks},(_,i)=><div className="calendar-day outside" key={'b'+i}/>)}{Array.from({length:days},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');return <div key={day} className={'calendar-day '+(day===today()?'is-today':'')}><span className="day-number">{i+1}</span>{sessions.filter(s=>s.fecha_inicio<=day&&s.fecha_fin>=day).map(s=><Link className={'calendar-event event-'+s.estatus.toLowerCase().replaceAll(' ','-')} key={s.id} to={'/cursos/sesiones/'+s.id}><strong>{s.nombre_curso}</strong><small>{s.estatus} · {s.sede}</small></Link>)}</div>;})}</div></div>:<div className="agenda">{sessions.length?sessions.map(s=><Link className="agenda-item" to={'/cursos/sesiones/'+s.id} key={s.id}><CalendarDays size={24}/><div><strong>{s.nombre_curso}</strong><p>{dateLabel(s.fecha_inicio)} — {dateLabel(s.fecha_fin)} · {s.sede}</p><small>{label(s.tipo)} · {s.horas} horas</small></div><span className={'badge event-'+s.estatus.toLowerCase().replaceAll(' ','-')}>{s.estatus}</span></Link>):<div className="empty"><h3>Sin sesiones este mes</h3><p>{staff?'Programa una sesión para comenzar.':'Consulta otro mes para encontrar cursos.'}</p></div>}</div>}
 </section><p className="footnote">El estado de cada sesión se calcula con sus fechas. Concluir una sesión no registra automáticamente una certificación.</p>
 <section className="table-panel"><div className="panel-heading"><h2>Catálogo de cursos</h2><span className="muted">{courses.length} cursos</span></div><div className="table-scroll"><table><thead><tr><th>Curso / institución</th><th>Tipo</th><th>Financiamiento</th><th>Horas</th>{staff&&<th>Acciones</th>}</tr></thead><tbody>{courses.map(c=><tr key={c.id}><td><strong>{c.nombre_curso}</strong><small>{c.institucion_impartidora}</small></td><td>{label(c.tipo)}</td><td>{label(c.fuente_financiamiento)}</td><td>{c.horas}</td>{staff&&<td><button className="text-button" onClick={()=>{setEditingCourse(c);setForm('curso');window.scrollTo({top:0,behavior:'smooth'});}}>Editar</button></td>}</tr>)}</tbody></table></div>{!courses.length&&!loading&&<div className="empty">Aún no hay cursos registrados.</div>}</section></>;
}

function CourseForm({existing,onSaved,onCancel}:{existing?:Course;onSaved:()=>void;onCancel:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[type,setType]=useState(existing?.tipo??'actualizacion');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await api('/cursos'+(existing?'/'+existing.id:''),{method:existing?'PUT':'POST',body:JSON.stringify({...d,horas:Number(d.horas),vigencia_meses:type==='competencias_basicas'?36:d.vigencia_meses?Number(d.vigencia_meses):null})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="surface record-form phase-form" onSubmit={submit}><h2>{existing?'Editar curso':'Registrar curso'}</h2><div className="form-grid"><label className="span-two">Nombre del curso *<input name="nombre_curso" defaultValue={existing?.nombre_curso} minLength={3} maxLength={200} required/></label><label>Tipo *<select name="tipo" value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><label>Fuente de financiamiento *<select name="fuente_financiamiento" defaultValue={existing?.fuente_financiamiento}>{['FASP','FOFISP','recurso_propio','otro'].map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><label>Institución impartidora *<input name="institucion_impartidora" defaultValue={existing?.institucion_impartidora} required minLength={2} maxLength={150}/></label><label>Duración en horas *<input name="horas" defaultValue={existing?.horas} type="number" min={1} max={10000} required/></label><label>Vigencia en meses<input name="vigencia_meses" key={type} type="number" min={1} max={120} defaultValue={type==='competencias_basicas'?36:existing?.vigencia_meses??undefined} readOnly={type==='competencias_basicas'}/><small>Opcional. Competencias básicas: 36 meses.</small></label></div><ErrorBox message={error}/><div className="form-actions"><button className="button secondary" type="button" disabled={busy} onClick={onCancel}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Guardando…':'Guardar curso'}</button></div></form>;
}

function SessionForm({courses,existing,onSaved,onCancel}:{courses:Course[];existing?:Session;onSaved:()=>void;onCancel:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await api('/curso-sesiones'+(existing?'/'+existing.id:''),{method:existing?'PUT':'POST',body:JSON.stringify({...d,cupo:Number(d.cupo)})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="surface record-form phase-form" onSubmit={submit}><h2>{existing?'Editar sesión':'Programar una sesión'}</h2>{!courses.length&&<p>Registra primero un curso en el catálogo.</p>}<div className="form-grid"><label className="span-two">Curso *<select name="curso_id" defaultValue={existing?.curso_id??''} required><option value="">Seleccionar curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.nombre_curso}</option>)}</select></label><label>Inicio *<input name="fecha_inicio" type="date" required defaultValue={existing?.fecha_inicio}/></label><label>Término *<input name="fecha_fin" type="date" required defaultValue={existing?.fecha_fin}/></label><label>Sede *<input name="sede" required minLength={2} maxLength={150} defaultValue={existing?.sede}/></label><label>Modalidad *<select name="modalidad" defaultValue={existing?.modalidad??'presencial'}>{['presencial','en_linea','mixta'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Cupo *<input name="cupo" type="number" min={1} max={10000} required defaultValue={existing?.cupo??25}/></label></div><ErrorBox message={error}/><div className="form-actions"><button className="button secondary" type="button" disabled={busy} onClick={onCancel}>Cancelar</button><button className="button primary" disabled={busy||!courses.length}>{busy?'Guardando…':'Guardar sesión'}</button></div></form>;
}

export function SessionDetail({user}:{user:User}){
 const {id}=useParams(),staff=user.rol!=='trabajador';
 const s=useData<Session>('/curso-sesiones/'+id),[offset,setOffset]=useState(0),rows=useData<Page<Enrollment>>(`/curso-sesiones/${id}/inscripciones?offset=${offset}`);
 const [editing,setEditing]=useState(false),[courses,setCourses]=useState<Course[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState<Enrollment|null>(null),[adding,setAdding]=useState(false),[success,setSuccess]=useState('');
 function saved(){rows.reload();s.reload();setSelected(null);setAdding(false);setSuccess('Inscripción guardada.');}
 async function edit(){setError('');try{setCourses(await allPages<Course>('/cursos'));setEditing(true);}catch(e){setError((e as Error).message);}}
 if(s.loading)return <Loading/>;if(s.error)return <><ErrorBox message={s.error}/><button className="button secondary" onClick={s.reload}>Reintentar</button><Link className="back-link" to="/cursos">Volver al calendario</Link></>;const session=s.data!;
 return <><Link className="back-link" to="/cursos">← Volver al calendario</Link><div className="page-heading"><div><span className="eyebrow">SESIÓN DE CAPACITACIÓN</span><h1>{session.nombre_curso}</h1><p>{dateLabel(session.fecha_inicio)} — {dateLabel(session.fecha_fin)}</p></div>{staff&&<button className="button secondary" onClick={edit}>Editar sesión</button>}</div><ErrorBox message={error}/>{success&&<div className="success" role="status">{success}</div>}
 {editing&&<SessionForm courses={courses} existing={session} onCancel={()=>setEditing(false)} onSaved={()=>{setEditing(false);s.reload();}}/>}
 <section className="surface"><dl className="facts">{[['Sede',session.sede],['Modalidad',label(session.modalidad)],['Estado',session.estatus],['Institución',session.institucion_impartidora],['Duración',`${session.horas} horas`],[staff?'Ocupación':'Cupo programado',staff?`${session.inscripciones_visibles} / ${session.cupo}`:String(session.cupo)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>
 <section className="table-panel history"><div className="panel-heading"><h2>{staff?'Inscripciones':'Mi inscripción'}</h2>{staff&&<button className="button primary" onClick={()=>{setAdding(!adding);setSelected(null);}}>Inscribir elemento</button>}</div>
 {(adding||selected)&&<EnrollmentForm key={selected?.id??'new'} sessionId={id!} existing={selected??undefined} onSaved={saved} onCancel={()=>{setAdding(false);setSelected(null);}}/>}
 <ErrorBox message={rows.error}/>{rows.error&&<button className="text-button" onClick={rows.reload}>Reintentar inscripciones</button>}{rows.loading?<Loading/>:rows.data?.items.length?<><div className="table-scroll"><table><thead><tr><th>Elemento</th><th>Estado</th><th>Calificación</th><th>Acciones</th></tr></thead><tbody>{rows.data.items.map(e=><tr key={e.id}><td><Link to={'/personal/'+e.personal_id}>{e.personal.nombre_completo}</Link><small>{e.personal.cuip}</small></td><td>{label(e.estatus)}</td><td>{e.calificacion??'Sin registrar'}</td><td>{staff?<button className="text-button" onClick={()=>{setSelected(e);setAdding(false);}}>Actualizar</button>:<Link to={'/personal/'+user.personal_id+'/bitacora'}>Abrir bitácora</Link>}</td></tr>)}</tbody></table></div><Pager offset={offset} more={rows.data.has_more} onChange={setOffset}/></>:!rows.error&&<div className="empty"><h3>{staff?'Sin inscripciones':'No tienes inscripción en esta sesión'}</h3><p>{staff?'Selecciona un elemento del directorio para inscribirlo.':'El área de capacitación administra las inscripciones.'}</p></div>}</section></>;
}

function EnrollmentForm({sessionId,existing,onSaved,onCancel}:{sessionId:string;existing?:Enrollment;onSaved:()=>void;onCancel:()=>void}){
 const [q,setQ]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[pid,setPid]=useState(existing?.personal_id??''),[name,setName]=useState(existing?.personal.nombre_completo??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const t=setTimeout(()=>{setSearch(q);setOffset(0);},250);return()=>clearTimeout(t);},[q]);
 const people=useData<Page<Person>>(`/personal?q=${encodeURIComponent(search)}&offset=${offset}`);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await api(`/curso-sesiones/${sessionId}/inscripciones`,{method:'POST',body:JSON.stringify({...d,personal_id:pid,calificacion:d.calificacion?Number(d.calificacion):null})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="surface phase-form" onSubmit={submit}><h3>{existing?'Actualizar inscripción':'Seleccionar elemento'}</h3>{!existing&&<><label>Buscar por nombre, CUIP o CURP<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar en el directorio"/></label><ErrorBox message={people.error}/>{people.loading?<Loading/>:<div className="person-options">{!people.error&&!people.data?.items.length&&<p className="muted">No se encontraron elementos. Prueba otro nombre o identificador.</p>}{people.data?.items.map(p=><button key={p.personal_id} type="button" aria-pressed={pid===p.personal_id} className={pid===p.personal_id?'chosen':''} onClick={()=>{setPid(p.personal_id);setName(p.nombre_completo);}}>{p.nombre_completo}<small>{p.cuip||p.curp}</small></button>)}</div>}<div className="action-row"><button type="button" className="text-button" disabled={!offset||people.loading} onClick={()=>setOffset(Math.max(0,offset-25))}>Anterior</button><button type="button" className="text-button" disabled={people.loading||!people.data?.has_more} onClick={()=>setOffset(offset+25)}>Siguiente</button></div></>}<p><strong>Elemento: </strong>{name||'Selecciona un elemento'}</p><div className="form-grid"><label>Estado<select name="estatus" defaultValue={existing?.estatus??'inscrito'}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Calificación (0–100)<input name="calificacion" type="number" min={0} max={100} step="0.01" defaultValue={existing?.calificacion??''}/></label></div><ErrorBox message={error}/><div className="form-actions"><button className="button secondary" type="button" disabled={busy} onClick={onCancel}>Cancelar</button><button className="button primary" disabled={!pid||busy}>{busy?'Guardando…':'Guardar inscripción'}</button></div></form>;
}
